### ISSUE TITLE
travis ci build failing but passing for py36 tests

### ISSUE THREAD

**Issue by mrodden** [IBM/keyprotect-python-client#1]
```py36 installed: certifi==2020.6.20,cffi==1.14.1,chardet==3.0.4,cryptography==3.0,idna==2.10,keyprotect==2.0.0,pycparser==2.20,pyOpenSSL==19.1.0,redstone==0.3.0,requests==2.24.0,six==1.15.0,urllib3==1.25.10
py36 run-test-pre: PYTHONHASHSEED='1505294956'
py36 run-test: commands[0] | python test/integration.py
Traceback (most recent call last):
  File "test/integration.py", line 89, in <module>
    main()
  File "test/integration.py", line 31, in main
    tm = bxauth.TokenManager(api_key=apikey)
NameError: name 'apikey' is not defined
___________________________________ summary ____________________________________
  py36: commands succeeded
  congratulations :)
The command "tox" exited with 0.```

Build link: https://travis-ci.com/github/IBM/keyprotect-python-client/jobs/365605575

**Comment by mrodden** [comment]
Fixed with 5e4ff871b375df50066b38f86fb9b7d6bc2eaef0
